version: '3'
services:
  web:
    image: "nginx:alpine"
    ports:
     - "80:80"
    volumes: 
     - ./nginx.vh.default.conf:/etc/nginx/conf.d/default.conf:ro
  app:
    build: .
  database:
    image: "postgres:alpine"
